### ISSUE TITLE
misspelled 'single' in the advanced example

### ISSUE THREAD

**Issue by defisit** [nickneos/Appdaemon-ZHA-Xiaomi-Aqara-Switch#1]
dimmer_main:
  module: zha_xiaomi_aqara_switch
  class: aqara_switch
  switch: '00:00:00:00:00:00:00:00'
  advanced:
    sinlge:
      action_type: cycle
      entity: light.bedroom
      parameters:
        - brightness_pct: 33
          kelvin: 3000
        - brightness_pct: 67
          kelvin: 3000
        - brightness_pct: 100
          kelvin: 3000
        - brightness_pct: 0
    double:
      action_type: turn_off
      entity:
        - group.all_lights
        - switch.bedroom_tv

**Comment by nickneos** [comment]
thanks corrected
