### ISSUE TITLE
Where do i put the config

### ISSUE THREAD

**Issue by ahmaddxb** [nickneos/Appdaemon-ZHA-Xiaomi-Aqara-Switch#2]
Where do I write this config to in Home Assistant?

dimmer_bedroom:
  module: zha_xiaomi_aqara_switch
  class: aqara_switch
  switch: '00:00:00:00:00:00:00:00'
  light: light.bedroom

**Comment by nickneos** [comment]
In your appdaemon folder.

If this is the first time you're setting up an appdaemon app, worth having a read through the appdaemon docs [here](https://appdaemon.readthedocs.io/en/latest/)
